---
###########
# Disable Nginx websites
#
# DESCRIPTION:
#     Disables nginx websites
#
# VARIABLES:
#     - parameter_nginx_sites_pattern - OPTIONAL   - system wildcard or sitename to disable
#     - role_nginx_enabled_sites_path - PREDEFINED - Location where active nginx configs are found
###########
- name: Disable Nginx websites
  file: path={{ item }}
        state=absent
  with_fileglob:
    - "{{ role_nginx_enabled_sites_path ~ '/' ~ (parameter_nginx_sites_pattern | default('*')) }}"
  sudo: true
  notify: Restart Nginx Service
