---
- include: ../../../common/tasks/apt/install_apt_packages.yml
  vars:
    parameter_apt_packages: "{{ role_mysql_packages }}"
    parameter_install_title: "Installing MySQL"
    parameter_apt_install_recommends: no
