---
###########
# Disable php5 modules
#
# DESCRIPTION:
#     Disable Php5 modules
#
# VARIABLES:
#     - parameter_php5_modules - REQUIRED - Array of Php5 modules
###########
- name: Enabling Php5 modules
  command: "php5dismod {{ item }}"
  with_items: parameter_php5_modules
  sudo: true
