---
###########
# Write php5 ini
#
# DESCRIPTION:
#     Writes to php5 ini
#
# VARIABLES:
#     - parameter_php5_ini_title                           - REQUIRED   - Title to use for action
#     - parameter_php5_ini_config[]                        - REQUIRED   - Configuration to write
#                                  .module                 - REQUIRED   - Name of module being updated (section in Php ini file)
#                                  .module_config[]        - REQUIRED   - Configuration to write to module
#                                                  .option - REQUIRED   - Option name
#                                                  .value  - REQUIRED   - Value to write
#     - role_php5_module_ini_directory                     - PREDEFINED - Directory in which to write configs
###########
- name: "{{ parameter_php5_ini_title }}"
  ini_file: dest="{{ role_php5_module_ini_directory ~ '/' ~ item.0.module ~ '.ini' }}"
    section={{ item.0.module }}
    option={{ item.1.option }}
    value={{ item.1.value }}
  with_subelements:
  - parameter_php5_ini_config
  - module_config
  sudo: true
